stages:
  - diagnostic

test-runner-access:
  stage: diagnostic

  image: alpine:3.20

  script:
    - |
      echo "========================================"
      echo "GITLAB RUNNER"
      echo "========================================"

      echo "Runner: ${CI_RUNNER_DESCRIPTION:-inconnu}"
      echo "Tags: ${CI_RUNNER_TAGS:-aucun}"

      echo
      echo "========================================"
      echo "TEST NEXUS RESEAU INTERNE"
      echo "========================================"

      wget \
        --server-response \
        --output-document=- \
        --timeout=10 \
        http://172.16.0.40:8084/v2/ \
        || true

      echo
      echo "========================================"
      echo "TEST NEXUS TAILSCALE"
      echo "========================================"

      wget \
        --server-response \
        --output-document=- \
        --timeout=10 \
        http://100.96.79.120:8084/v2/ \
        || true

      echo
      echo "========================================"
      echo "OUTIL DE CONSTRUCTION"
      echo "========================================"

      command -v docker || true
      docker version || true

  rules:
    - if: '$CI_COMMIT_BRANCH'