{{- range .Values.persistence }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sapixi.fullname" $ }}-{{ .name }}
  labels:
    {{- include "sapixi.labels" $ | nindent 4 }}
spec:
  accessModes:
    - {{ .accessMode }}
  {{- if .storageClass }}
  storageClassName: {{ .storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
