apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: projet-test2-test-local
  namespace: argocd
  labels:
    sapixi.io/managed: 'true'
    sapixi.io/project: projet-test2
    sapixi.io/environment: test-local
spec:
  description: Projet Argo CD géré par SApixi pour projet-test2 dans test-local.
  sourceRepos:
  - http://172.16.0.40:8081/repository/sapixi-helm/
  destinations:
  - server: https://100.96.79.120:6443
    namespace: pixismart-test
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true
