nameOverride: source
fullnameOverride: helloword-source
replicaCount: 1
image:
  repository: 100.96.79.120:8081/helloword/source
  tag: fb93e5c6d136dc19edde4bb421b18fd0d931a515
  pullPolicy: IfNotPresent
imagePullSecrets:
- name: registry-credentials
podAnnotations:
  sapixi.io/project: helloword
  sapixi.io/component: source
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 10001
  capabilities:
    drop:
    - ALL
service:
  enabled: true
  type: ClusterIP
  port: 5000
  targetPort: 5000
ingress:
  enabled: true
  className: nginx
  annotations: {}
  host: pixismart-test.local
  path: /
  pathType: Prefix
  tls: []
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
probes:
  startup:
    path: /
    enabled: true
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 6
    initialDelaySeconds: 10
  liveness:
    path: /
    enabled: true
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 6
    initialDelaySeconds: 10
  readiness:
    path: /
    enabled: true
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 6
    initialDelaySeconds: 10
config:
  PORT: ''
secrets:
  create: false
  existingSecretName: ''
  values: {}
persistence: []
migration:
  enabled: false
  command: flask db upgrade
  backoffLimit: 1
nodeSelector: {}
tolerations: []
affinity: {}
