{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sapixi.fullname" . }}-secret
  labels:
    {{- include "sapixi.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $value := .Values.secrets.values }}
  {{ $name }}: {{ required (printf "La valeur du secret %s est obligatoire" $name) $value | quote }}
  {{- end }}
{{- end }}
